name: asset_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #Network Connections
  http: ^1.2.2
  web_socket_channel: ^3.0.1

  #Web html tools
  html: ^0.15.4

  #state management
  flutter_bloc: ^8.1.6
  provider: ^6.1.2

  #Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  firebase_app_check: ^0.3.1+2

  #Json operations
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
